# 第3部分 php常用功能模块篇
## 第13章 php的错误和异常处理
- [ ] 错误处理
- [ ] 异常处理

---

### 13.1 错误处理  
#### 13.1.1 错误报告级别  
#### 13.1.2 调整错误报告级别  


```html
<html>
	<head><title>测试错误报告</title></head>
	<body>
		<h2>测试错误报告</h2>
		<?php
			/*开启php.ini中的display_errors指令，只有该指令开启如果有错误报告才能输出*/
			ini_set('display_errors', 1);  
			/*通过error_reporting()函数设置在本脚本中，输出所有级别的错误报告*/
			error_reporting( E_ALL );
			/*“注意(notice)”的报告，不会阻止脚本的执行，并且可能不一定是一个问题 */
			getType( $var );        		//调用函数时提供的参数变量没有在之前声明
			/*“警告(warning)”的报告，指示一个问题，但是不会阻止脚本的执行 */
			getType();           			//调用函数时没有提供必要的参数
			/*“错误(error)”的报告，它会终止程序，脚本不会再向下执行 */
			get_Type();          			//调用一个没有被定义的函数
		?>
	</body>
</html>


```

#### 13.1.3 使用trigger_error()函数来替代die()  
#### 13.1.4 自定义错误处理  


```php
<?php
	error_reporting(0);					//屏蔽程序中的错误
	
	/**
		定义Error_Handler函数，作为set_error_handler()函数的第一个参数"回调"
		@param	int		$error_level		错误级别
		@param	string	$error_message	错误信息
		@param	string	$file			错误所在文件
		@param	int		$lin				错误所在行数
	*/
	function error_handler($error_level, $error_message, $file, $line) {
		$EXIT = FALSE;
		switch( $error_level ) {
			//提醒级别
			case E_NOTICE:
			case E_USER_NOTICE;
				$error_type = 'Notice'; break;
				
			//警告级别
			case E_WARNING:
			case E_USER_WARNING:
				$error_type = 'Warning'; break;
			
			//错误级别
			case E_ERROR:
			case E_USER_ERROR:
				$error_type = 'Fatal Error';
				$EXIT = TRUE; break;
				
			//其他末知错误
			default:
				$error_type = 'Unknown';
				$EXIT = TRUE; break;
		}
		
		//直接打印错误信息， 也可以写文件，写数据库，反正错误信息都在这，任你发落
		printf ("<font color='#FF0000'><b>%s</b></font>: %s in <b>%s</b> on line <b>%d</b><br>\n", $error_type, $error_message, $file, $line);
		
		//如果错误影响到程序的正常执行，跳转到友好的错误提示页面
		if(TRUE == $EXIT) {
			echo '<script>location = "err.html"; </script>';
		}
	}
	
	//这个才是关键点， 把错误的处理交给error_handler()
	set_error_handler('error_handler');
	
	//使用末定义的变量要报 notice 的
	echo $novar;
	
	//除以0要报警告的
	echo 3/0;
	
	//自定义一个错误
	trigger_error('Trigger a fatal error', E_USER_ERROR);

```

#### 13.1.5 写错误日志 

```php
<?php   
	if(!Ora_Logon($username, $password)){   
		//将错误消息写入到操作系统日志中
		error_log("Oracle数据库不可用!", 0);       	
	}
	
	if(!($foo=allocate_new_foo()){
		//发送到管理员邮箱中
		error_log("出现大麻烦了!", 1, "webmaster@www.mydomain.com");   
	}
	
	//发送到本机对应5000端口的服务器中
	error_log("搞砸了!",   2,   "localhost:5000");    	
	//发送到指定的文件中
	error_log("搞砸了!",   3,   "/usr/local/errors.log"); 	



```


```php
<?php
	define_syslog_variables();
	
	openlog("PHP5", LOG_PID , LOG_USER);
	syslog(LOG_WARNING, "警告报告向syslog中发送的演示，警告时间：".date("Y/m/d H:i:s"));
	
	closelog();



```






---

### 13.2 异常处理  
#### 13.2.1 异常处理实现  

```php
<?php
	try {
		$error = 'Always throw this error';
		throw new Exception($error); 						//创建一个异常对象，通过throw语句抛出
		echo 'Never executed';        						//从这里开始，try代码块内的代码将不会再被执行
	} catch (Exception $e) {
		echo 'Caught exception: ',  $e->getMessage(), "\n"; //输出捕获的异常消息
	}
	echo 'Hello World';              						//程序没有崩溃继续向下执行



```

#### 13.2.2 扩展php内置的异常处理类  

```php
<?php
	class Exception {
 	   protected $message = 'Unknown exception';   			//异常信息
 	   protected $code = 0;                        			//用户自定义异常代码
 	   protected $file;                           		 	//发生异常的文件名
 	   protected $line;                           		 	//发生异常的代码行号

 	   function __construct($message = null, $code = 0){}	//构造方法

 	   final function getMessage(){}                		//返回异常信息
 	   final function getCode(){}                  			//返回异常代码
 	   final function getFile(){}                    		//返回发生异常的文件名
       final function getLine(){}                   		//返回发生异常的代码行号
   	   final function getTrace(){}                  		//backtrace() 数组
  	   final function getTraceAsString(){}           		//已格成化成字符串的 getTrace() 信息

 	   /* 可重载的方法 */
 	   function __toString(){}                     			//可输出的字符串
	}



```


```php
<?php
	/* 自定义的一个异常处理类，但必须是扩展内异常处理类的子类 */
	class MyException extends Exception{
		//重定义构造器使第一个参数 message 变为必须被指定的属性
		public function __construct($message, $code=0){
			//可以在这里定义一些自己的代码
			//建议同时调用 parent::construct()来检查所有的变量是否已被赋值
			parent::__construct($message, $code);
		}
		
		//重写父类方法，自定义字符串输出的样式
		public function __toString() {     	
			return __CLASS__.":[".$this->code."]:".$this->message."<br>";
		}
		
		//为这个异常自定义一个处理方法
		public function customFunction() { 	
			echo "按自定义的方法处理出现的这个类型的异常<br>";
		}
	}
	
	try {                               	//使用自定义的异常类捕获一个异常，并处理异常
		$error = '允许抛出这个错误';       
		throw new MyException($error);  	//创建一个自定义的异常类对象，通过throw语句抛出
		echo 'Never executed';             	//从这里开始，try代码块内的代码将不会再被执行
	} catch (MyException $e) {             	//捕获自定义的异常对象
		echo '捕获异常: '.$e;              	//输出捕获的异常消息
		$e->customFunction();            	//通过自定义的异常对象中的方法处理异常
	}
	echo '你好呀';                       	//程序没有崩溃继续向下执行



```

#### 13.2.3 捕获多个异常  

```php
<?php
	/* 自定义的一个异常处理类，但必须是扩展内异常处理类的子类 */
	class MyException extends Exception{
		//重定义构造器使第一个参数 message 变为必须被指定的属性
		public function __construct($message, $code=0){
			//可以在这里定义一些自己的代码
			//建议同时调用 parent::construct()来检查所有的变量是否已被赋值
			parent::__construct($message, $code);
		}
		//重写父类中继承过来的方法，自定义字符串输出的样式
		public function __toString() {
			return __CLASS__.":[".$this->code."]:".$this->message."<br>";
		}

		//为这个异常自定义一个处理方法
		public function customFunction() {
			echo "按自定义的方法处理出现的这个类型的异常";
		}
	}
	
	/* 创建一个用于测试自定义扩展的异常类MyException */
	class TestException {
		public $var;                    					//用来判断对象是否创建成功的成员属性

		function __construct($value=0) {    				//通过构造方法的传值决定抛出的异常
			switch($value){             					//对传入的值进行选择性的判断
				case 1:                						//传入参数1，则抛出自定义的异常对象
					throw new MyException("传入的值“1” 是一个无效的参数", 5); break;
				case 2:              						//传入参数2，则抛出PHP内置的异常对象
					throw new Exception("传入的值“2”不允许作为一个参数", 6); break;
				default:               						//传入参数合法，则不抛出异常
					$this->var=$value; 	break;				//为对象中的成员属性赋值
					
			}
		}
	}
	
    /* 示例1，在没有异常时，程序正常执行，try中的代码全部执行并不会执行任何catch区块 */
	try{
		$testObj = new TestException();          		 	//使用默认参数创建异常的测试类对象
		echo "***********<br>";               				//没有抛出异常这条语句就会正常执行
	}catch(MyException $e){                    				//捕获用户自定义的异常区块
		echo "捕获自定义的异常：$e <br>";     				//按自定义的方式输出异常消息
		$e->customFunction();                 				//可以调用自定义的异常处理方法
	}catch(Exception $e) {                      			//捕获PHP内置的异常处理类的对象
		echo "捕获默认的异常：".$e->getMessage()."<br>";    //输出异常消息
	} 	
	var_dump($testObj);          //判断对象是否创建成功，如果没有任何异常，则创建成功

    /* 示例2，抛出自定义的异常，并通过自定义的异常处理类捕获这个异常并处理 */
	try{	
		$testObj1 = new TestException(1);        			 //传1时，抛出自定义异常
		echo "***********<br>";               				 //这个语句不会被执行
	}catch(MyException $e){                    				 //这个catch区块中的代码将被执行
		echo "捕获自定义的异常：$e <br>";
		$e->customFunction();
	}catch(Exception $e) {                     				//这个catch区块不会执行
		echo "捕获默认的异常：".$e->getMessage()."<br>";
	} 	
	var_dump($testObj1);                      				//有异常产生，这个对象没有创建成功

    /* 示例2，抛出内置的异常，并通过自定义的异常处理类捕获这个异常并处理 */
	try{
		$testObj2 = new TestException(2);        			//传入2时，抛出内置异常
		echo "***********<br>";             				//这个语句不会被执行
	}catch(MyException $e){                  				//这个catch区块不会执行
		echo "捕获自定义的异常：$e <br>";
		$e->customFunction();
	}catch(Exception $e) {                    				//这个catch区块中的代码将被执行
		echo "捕获默认的异常：".$e->getMessage()."<br>";
	} 	
	var_dump($testObj2);                    			    //有异常产生，这个对象没有创建成功



```


```php


```









### 13.3 小结

---

- [ ] 本章必须掌握的知识点
- [ ] 本章需要了解的内容
- [ ] 本章需要拓展的内容
- [ ] 本章的学习建议